name: test
on: [push]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu
          - macOS

    name: "${{ matrix.platform }}"

    runs-on: ${{ matrix.platform }}-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest
      - name: Format check
        run: gofumpt -l .

      - name: Go test
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: ${{ matrix.platform }}
